### PR TITLE
Update default ubuntu images for pipelines

### PR DESCRIPTION
**Pull request by c-ryan-k**
We've started getting warnings as ubuntu-18.04 images are deprecated on ADO.

This update pushes our ubuntu images up to 20.04 (which is also the same as ubuntu-latest currently), but also provides support for testing pipelines on ubuntu 22.04

---
This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or contact [opencode@microsoft.com](mailto:opencode@microsoft.com) with any additional questions or comments.

Thank you for contributing to the IoT extension!

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

Intent for Production

- [ ] It is expected that pull requests made to default or core branches such as `dev` or `main` are of production grade. Corollary to this, any merged contributions to these branches may be deployed in a public release at any given time. By checking this box, you agree and commit to the expected production quality of code.

Basic expectations

- [ ] If introducing new functionality or modified behavior, are they backed by unit and/or integration tests?
- [ ] In the same context as above are command names and their parameter definitions accurate? Do help docs have sufficient content?
- [ ] Have **all** the relevant unit **and** integration tests pass? i.e. `pytest <project root> -vv`. Please provide evidence in the form of a screenshot showing a succesful run of tests locally OR a link to a test pipeline that has been run against the change-set.
- [ ] Have linter checks passed using the `.pylintrc` and `.flake8` rules? Look at the CI scripts for example usage.
- [ ] Have extraneous print or debug statements, commented out code-blocks or code-statements (if any) been removed from the surface area of changes?
- [ ] Have you made an entry in HISTORY.rst which concisely explains your user-facing feature or change?

Azure IoT CLI maintainers reserve the right to enforce any of the outlined expectations.

A PR is considered **ready for review** when all basic expectations have been met (or do not apply).

### CODE REVIEW

**Comment by vilit1** [comment]
pipeline run?

**Comment by c-ryan-k** [comment]
> pipeline run?

Merge was completed in this PR, waiting for some other pipelines to finish before I kick off dry-runs of the nightly and release pipelines to ensure we're good on 20.04 at least.

May do some testing today or tomorrow to try out 22.04, but think this is safe to include as a runtime option since it isn't a default value.

**Comment by digimaun** [comment]
Lets get this in soon

image

**Review by digimaun — APPROVED** [review]

**Comment by c-ryan-k** [comment]
> Lets get this in soon
> 
> image

Trying to pin down a test failure in ADT while running this merge branch against our current release pipeline. Not sure if it's at all related to the jump from 18 to 20, but want to verify and see the ADT tests pass on 20 before moving forward.

If necessary, I can also modify this PR to still set the default to 20.04, but leave 18.04 as an option for break-glass scenarios if we need a release and 20 is failing for some reason.

**Review by vilit1 — APPROVED** [review]

**Pull request merged**
