### PR TITLE
Pipeline updates - Add reference doc validation and fix warnings

### PR DESCRIPTION
**Pull request by c-ryan-k**
- Adds a step to the merge pipeline to validate reference document generation for the CLI extension index
- Removes semver patch specifier `.x` from python version arguments to fix warnings in pipelines
- Updates MacOS unit test image on merge pipeline from `10.15` to `11` as 10.15 is now deprecated

Currently the reference document validation job is only used in the merge pipeline, but we could easily add this to the build stage of the release (or nightly) pipelines as well.

---
This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or contact [opencode@microsoft.com](mailto:opencode@microsoft.com) with any additional questions or comments.

Thank you for contributing to the IoT extension!

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

Intent for Production

- [x] It is expected that pull requests made to default or core branches such as `dev` or `main` are of production grade. Corollary to this, any merged contributions to these branches may be deployed in a public release at any given time. By checking this box, you agree and commit to the expected production quality of code.

Basic expectations

- [ ] If introducing new functionality or modified behavior, are they backed by unit and/or integration tests?
- [ ] In the same context as above are command names and their parameter definitions accurate? Do help docs have sufficient content?
- [ ] Have **all** the relevant unit **and** integration tests pass? i.e. `pytest <project root> -vv`. Please provide evidence in the form of a screenshot showing a succesful run of tests locally OR a link to a test pipeline that has been run against the change-set.
- [ ] Have linter checks passed using the `.pylintrc` and `.flake8` rules? Look at the CI scripts for example usage.
- [ ] Have extraneous print or debug statements, commented out code-blocks or code-statements (if any) been removed from the surface area of changes?
- [ ] Have you made an entry in HISTORY.rst which concisely explains your user-facing feature or change?

Azure IoT CLI maintainers reserve the right to enforce any of the outlined expectations.

A PR is considered **ready for review** when all basic expectations have been met (or do not apply).

### CODE REVIEW

**Comment by c-ryan-k** [comment]
Test run - https://dev.azure.com/azureiotdevxp/aziotcli/_build/results?buildId=6189&view=results

**Comment by digimaun** [comment]
LGTM - we should also add this as a step to the create release pipeline as we do with the command table linter https://github.com/Azure/azure-iot-cli-extension/blob/dev/.azure-devops/create-release.yml#L146

**Review by digimaun — APPROVED** [review]

**Comment by c-ryan-k** [comment]
> LGTM - we should also add this as a step to the create release pipeline as we do with the command table linter https://github.com/Azure/azure-iot-cli-extension/blob/dev/.azure-devops/create-release.yml#L146

Added that commit and tested:
https://dev.azure.com/azureiotdevxp/aziotcli/_build/results?buildId=6198&view=logs&s=859b8d9a-8fd6-5a5c-6f5e-f84f1990894e&j=3e99c488-073e-58ad-3836-9f05f03bc0ca

**Comment by digimaun** [comment]
> > LGTM - we should also add this as a step to the create release pipeline as we do with the command table linter https://github.com/Azure/azure-iot-cli-extension/blob/dev/.azure-devops/create-release.yml#L146
> 
> Added that commit and tested: https://dev.azure.com/azureiotdevxp/aziotcli/_build/results?buildId=6198&view=logs&s=859b8d9a-8fd6-5a5c-6f5e-f84f1990894e&j=3e99c488-073e-58ad-3836-9f05f03bc0ca

Thank you, :shipit: Ship it

**Pull request merged**
